function getEventsMock() {
    return JSON.stringify([
        [
            {
                name: 'IPC Promotions, Mandeep team',
                lang: 'Hindi',
                allocation: [[], [[132, '2024-06-17T16:00:00', '2024-06-17T17:00:00']]],
                details: [
                    'No',
                    '',
                    '[[],[[132,"2024-06-17T16:00:00","2024-06-17T17:00:00"]]]',
                    'Room 132\n16.00 to 17.00\n',
                    'example@gmail.com',
                    'Name',
                    'example@gmail.com',
                    '12345',
                    '',
                    '2024-06-16T18:30:00.000Z',
                    '1899-12-30T10:38:50.000Z',
                    '1899-12-30T11:38:50.000Z',
                    '1899-12-29T19:38:50.000Z',
                    'IPC Promotions, Mandeep team',
                    'Hindi',
                    'Yes',
                    '2024-06-17T08:03:05.846Z',
                    12345,
                    'Other',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    'Davinci resolve',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                ],
            },
            {
                name: 'IPC Promotions Mandeep team',
                lang: 'English',
                allocation: [[], [[132, '2024-06-17T17:00:00', '2024-06-17T19:00:00']]],
                details: [
                    'No',
                    '',
                    '[[],[[132,"2024-06-17T17:00:00","2024-06-17T19:00:00"]]]',
                    'Room 132\n17:00 - 19:00\nThey wanted extended timings after first session',
                    'example@gmail.com',
                    'Name',
                    'example@gmail.com',
                    '+12345',
                    '',
                    '2024-06-16T18:30:00.000Z',
                    '1899-12-30T14:23:50.000Z',
                    '1899-12-30T16:08:50.000Z',
                    '1899-12-29T20:23:50.000Z',
                    'IPC Promotions Mandeep team',
                    'English',
                    'Yes',
                    '2024-06-17T08:06:51.411Z',
                    12345,
                    'Other',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    'Da vinci resolve',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                ],
            },
            {
                name: 'Monthly Satsang',
                lang: 'German',
                allocation: [
                    [],
                    [['upcoming', '2024-06-06T05:30:00.000Z', '2024-06-06T06:30:00.000Z']],
                ],
                details: [
                    'No',
                    '',
                    '',
                    '',
                    'example@gmail.com',
                    'kok',
                    'joip',
                    'jlk',
                    '',
                    '2024-06-05T18:30:00.000Z',
                    '1899-12-30T05:38:50.000Z',
                    '1899-12-30T06:38:50.000Z',
                    '1899-12-29T19:38:50.000Z',
                    'Monthly Satsang',
                    'German',
                    'Yes',
                    '2024-06-17T08:05:35.933Z',
                    'jio',
                    'YouTube',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    'sfds',
                    'Live chat is needed',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                ],
            },
            {
                name: 'Hybrid childrens program (Tamil)\n',
                lang: 'Tamil',
                allocation: [
                    [],
                    [
                        [132, '2024-07-01T07:30:00', '2024-07-01T17:00:00'],
                        [132, '2024-07-01T07:30:00', '2024-07-01T17:00:00'],
                    ],
                ],
                details: [
                    'No',
                    '',
                    '[[],[[132,"2024-07-01T07:30:00","2024-07-01T17:00:00"], [132,"2024-07-01T07:30:00","2024-07-01T17:00:00"]]]',
                    'Room 132 \n30th June - 8th July\n\nHybrid childrens program (Tamil) dry run\n11.00 - 8.00\nHybrid childrens program (Tamil)\n7.30 - 17.00',
                    'example@gmail.com',
                    'Name',
                    'example@gmail.com',
                    12345,
                    '9am to 11am\n11.30am to 1.30pm\n2.30pm to 4.30pm\n\nWe want a room from 29th evening for setup\n30th dry run \n\nJuly 1-8th we want the hall full day ideally ',
                    '2024-06-29T18:30:00.000Z',
                    '1899-12-30T02:08:50.000Z',
                    '1899-12-30T11:38:50.000Z',
                    '1899-12-30T04:08:50.000Z',
                    'Hybrid childrens program (Tamil)\n',
                    'Tamil',
                    'Yes',
                    '2024-06-17T11:25:02.021Z',
                    12345,
                    'Other',
                    '',
                    "Don't know ",
                    'Childrens Program (Tamil)',
                    'Yes',
                    'No',
                    'No',
                    'Yes',
                    'Enable focus mode when meeting starts',
                    '',
                    '',
                    '',
                    '',
                    'Zoom ( tnk)',
                    'No need to create zoom link',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                ],
            },
            {
                name: 'DES yoga day webinar ',
                lang: 'Hindi',
                allocation: [
                    [],
                    [['upcoming', '2024-06-21T01:30:00.000Z', '2024-06-21T04:00:00.000Z']],
                ],
                details: [
                    'No',
                    '',
                    '',
                    'Webinar for joy and Well being \n07.30-9.30 | 18.00-20.00\n\nRoom 135',
                    'example@gmail.com',
                    'Sanket ',
                    'example@gmail.com',
                    12345,
                    'Namaskaram akka 21st ko ek webinar karna hai\n\n Date:\n21 June \n\nTime: \n1st session - 7.30am \n2nd session - 6pm \n\nTitle: \nWebinar for joy and well being \n\nFor \nDeccan Education Society, Pune\n\n Kya koi room available hai?\n\n Shivapadam mai',
                    '2024-06-20T18:30:00.000Z',
                    '1899-12-30T01:38:50.000Z',
                    '1899-12-30T04:08:50.000Z',
                    '1899-12-29T21:08:50.000Z',
                    'DES yoga day webinar ',
                    'Hindi',
                    'Yes',
                    '2024-06-18T03:28:16.242Z',
                    12345,
                    'YouTube',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    'Webinar for joy and Well being ',
                    'Live chat is needed, Video to be accessible after the session ends',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                ],
            },
            {
                name: 'International day of yoga',
                lang: 'Not confirmed',
                allocation: [
                    [],
                    [['upcoming', '2024-06-20T18:30:00.000Z', '2024-06-20T18:30:00.000Z']],
                ],
                details: [
                    'No',
                    '',
                    '',
                    'Rejected.\nWe cannot book for entire day, need timings.',
                    'example@gmail.com',
                    'Name',
                    'example@gmail.com',
                    12345,
                    'Namaskaram 🙏\nAs many requests are coming for conducting international day of yoga - free yoga sessions, we want to book one room for 21, 22, 23. For any other request we will fill seperate form. ',
                    '2024-06-20T18:30:00.000Z',
                    '1899-12-29T18:38:50.000Z',
                    '1899-12-29T18:38:50.000Z',
                    '1899-12-29T18:38:50.000Z',
                    'International day of yoga',
                    'Not confirmed',
                    'No',
                    '2024-06-18T10:12:20.986Z',
                    12345,
                    'Other',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    'Not confirmed yet',
                    'Not confirmed yet',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                ],
            },
            {
                name: 'IDY',
                lang: 'Not confirmed',
                allocation: [
                    [],
                    [['upcoming', '2024-06-21T01:00:00.000Z', '2024-06-21T04:00:00.000Z']],
                ],
                details: [
                    'No',
                    '',
                    '',
                    '',
                    'example@gmail.com',
                    'Name',
                    'example@gmail.com',
                    12345,
                    '',
                    '2024-06-20T18:30:00.000Z',
                    '1899-12-30T01:08:50.000Z',
                    '1899-12-30T04:08:50.000Z',
                    '1899-12-29T21:38:50.000Z',
                    'IDY',
                    'Not confirmed',
                    'No',
                    '2024-06-18T16:10:41.660Z',
                    '12345',
                    'YouTube',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    'YouTube link is already created: ',
                    'None',
                    'Live chat not confirmed from organizers yet.',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                ],
            },
            {
                name: 'IDY',
                lang: 'Not confirmed',
                allocation: [
                    [],
                    [['upcoming', '2024-06-21T13:00:00.000Z', '2024-06-21T15:30:00.000Z']],
                ],
                details: [
                    'No',
                    '',
                    '',
                    '',
                    'example@gmail.com',
                    'Name ',
                    'example@gmail.com',
                    '12345',
                    '',
                    '2024-06-20T18:30:00.000Z',
                    '1899-12-30T13:08:50.000Z',
                    '1899-12-30T15:38:50.000Z',
                    '1899-12-29T21:08:50.000Z',
                    'IDY',
                    'Not confirmed',
                    'No',
                    '2024-06-18T16:16:27.076Z',
                    '12345',
                    'YouTube',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    'YouTube link generated.',
                    'None',
                    'Live chat not confirmed yet. ',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                ],
            },
        ],
        [
            'Cancellation',
            'notification',
            'Allocation Data',
            'Manual Allocation',
            'Email Address',
            'Name of streaming volunteer',
            'Email Address of streaming volunteer',
            'WhatsApp number of streaming volunteer',
            'Remarks',
            'Start Date',
            'Session Start Time (including Yogapadhi)',
            'Session End Time (including Yogapadhi)',
            'Duration',
            'Program name / details',
            'Program Language',
            'Is it a recurring session?',
            'Timestamp',
            'Contact number of streaming volunteer',
            'Name of the platform being used',
            'If platform is chosen as "other", please specify the name of the platform',
            'Approximate Number of Participants for Zoom',
            'Title needed for the Zoom link',
            'Waiting Room for Zoom session',
            'Enable Continuous Meeting Chat for Zoom session',
            'Is Registration Required for Zoom session?',
            'Does Zoom session need to be streamed to Youtube ?',
            'Other features in Zoom session',
            'Remarks for Zoom Link',
            'Title needed for the YouTube link',
            'YouTube Features',
            'Remarks for YouTube link',
            'Name of the other platform',
            'Remarks for other platform',
            'Name of the platform',
            'Remarks',
            'Cancellation',
            'Email Address',
            'Duration',
            'If recurring session, please mention end date.',
            'Enable Continuous Meeting Chat',
            'Waiting Room',
            'Title needed for the link',
            'Is DVR needed ?',
            'Approximate Number of Participants',
            'Title needed for the link',
            'Enable Continuous Meeting Chat',
            'Waiting Room',
            'Is Registration Required ?',
            'Does Zoom session need to be streamed to Youtube ?',
            'Others',
            'Remarks',
            'Approximate Number of Participants',
            'Title needed for the link',
            'Enable Continuous Meeting Chat',
            'Waiting Room',
            'Is Registration Required ?',
            'Does Zoom session need to be streamed to Youtube ?',
            'Others',
            'Remarks',
        ],
    ]);
    return JSON.stringify([
        [
            {
                name: 'IE 7 days',
                lang: 'English',
                allocation: [
                    [],
                    [
                        [
                            '131',
                            new Date('2024-06-07T13:30:00.000Z'),
                            new Date('2024-06-07T15:30:00.000Z'),
                        ],
                    ],
                ],
                details: ['xyz', '12345 12345', '2024-06-08T01:30:00.000Z'],
            },
            {
                name: 'Sadhguru Sahabhagi',
                lang: 'Hindi',
                allocation: [
                    [],
                    [
                        [
                            'upcoming',
                            new Date('2024-06-07T01:30:00.000Z'),
                            new Date('2024-06-07T05:00:00.000Z'),
                        ],
                    ],
                ],
                details: ['123', '12345 12345', '2024-06-08T01:30:00.000Z'],
            },
            {
                name: 'Sadhguru Sahabhagi long title blah blah',
                lang: 'Hindi',
                allocation: [
                    [],
                    [
                        [
                            '131',
                            new Date('2024-06-07T01:30:00.000Z'),
                            new Date('2024-06-07T05:00:00.000Z'),
                        ],
                    ],
                ],
                details: ['xyz123', '12345 12345', '2024-06-08T01:30:00.000Z'],
            },
            {
                name: 'Sadhguru Sahabhagi',
                lang: 'Hindi',
                allocation: [
                    [],
                    [
                        [
                            '132',
                            new Date('2024-06-08T01:30:00.000Z'),
                            new Date('2024-06-08T05:00:00.000Z'),
                        ],
                    ],
                ],
                details: ['abc', '12345 12345', '2024-06-08T01:30:00.000Z'],
            },
        ],
        [
            'Column 1',
            'WhatsApp number of streaming volunteer',
            'Session Start Time (including Yogapadhi)',
        ],
    ]);
}
